Remove WaitForEvents for CLBlast to improve performance
fixstars/clpy pull request #180
Opened 2019-02-14 09:09 UTC by vorj

Task for #174 .

This PR removes calling `WaitForEvents` for CLBlast.
It seems that the performance becomes better.

2019-02-17 08:35 UTC, LWisteria requested changes
Can you confirm performance improvment? (on Chainer example mnist and/or resnet50)

2019-02-19 05:59 UTC, vorj commented
c684684 -> 994974e  
`train_mnist.py` on Primary: 118.03 -> 101.619

(Please wait for other performance checks...)

2019-02-28 06:50 UTC, vorj commented
@LWisteria please check the above performance report.

2019-03-01 02:46 UTC, LWisteria requested changes
@vorj Thanks for the performance report! I'm glad to hear those improvements. I request you as follows:

* There is also [clWaitForEvents on the dgemm](https://github.com/fixstars/clpy/blob/994974ea6242c33663dbf8840e6ef2110211be19/clpy/backend/opencl/clblast/clblast.pyx#L142). Why don't you remove it?
* [cl_event object](https://github.com/fixstars/clpy/blob/994974ea6242c33663dbf8840e6ef2110211be19/clpy/backend/opencl/clblast/clblast.pyx#L74) is not needed anymore. Why don't you remove it?

2019-03-14 06:20 UTC, vorj commented
@LWisteria I misunderstood what `cl_event` does. Now `cl_event` variables have been purged and I am rejudging the performance.
I will make a proper performance report later, but it seems that the performance improves about **x1.5 faster**.

2019-03-14 06:22 UTC, LWisteria commented
> x1.5 faster

Good! compared to what? (than https://github.com/fixstars/clpy/pull/180#issuecomment-464996117)?

2019-03-14 06:25 UTC, vorj commented
Compared to c684684 .

2019-03-14 06:35 UTC, LWisteria commented
OK. It's almost same as https://github.com/fixstars/clpy/pull/180#issuecomment-464996117. So, why do you need to measure performance again?

2019-03-14 06:50 UTC, vorj commented
Because I removed [`WaitForEvents` on dgemm](https://github.com/fixstars/clpy/pull/180/commits/ad8d825cb441984a2d022d9523b6714753e2e0d5#diff-d9c9d850dfd0c7bf59767f190af87a16L142) and [`ReleaseEvent`s](https://github.com/fixstars/clpy/pull/180/commits/ad8d825cb441984a2d022d9523b6714753e2e0d5#diff-d9c9d850dfd0c7bf59767f190af87a16L89) on 
ad8d825, and I couldn't make judgement that the performance is not affected without re-measuring. (Then, I confirmed that the performance improves much more.)

2019-03-14 06:51 UTC, LWisteria commented
> that the performance improves much more

How much more? It seems almost same for me.

2019-03-14 07:12 UTC, vorj commented
I think that `653.018 / 498.742` is not almost same as `1.5` .

2019-03-14 09:42 UTC, vorj commented
c684684 -> ad8d825  
- `train_mnist.py` on Primary: 118.03 -> 77.8813 (x1.52)
- `train_imagenet.py` (resnet50) on old Primary: 2079.21 -> 1600.07 (x1.30)
- `train_mnist.py` on Secondary: 71.8251 -> 48.8838 (x1.47)
- `train_imagenet.py` (resnet50) on Secondary: 653.018 -> 410.303 (x1.59)

Resnet50 on old Primary is worse than 994974e, but it seems that the performance has became better on the whole.

2019-03-26 06:34 UTC, LWisteria commented
@vorj Can I merge?

2019-03-26 09:46 UTC, vorj commented
@LWisteria It's ready to review. If there is nothing to fix, please merge it.

2019-03-26 09:47 UTC, LWisteria approved these changes
LGTM

2019-03-26 09:47 UTC, merged