Some Refactoring
fixstars/clpy pull request #223
Opened 2019-04-05 11:06 UTC by vorj

This PR contains below changes:
- Set default argument for`cl_event` parameter of `clpy.backend.opencl.api.EnqueueFooBar`
    - Current ClPy waits finishing kernels execution when [reading](https://github.com/fixstars/clpy/blob/1542f0b9f4d686e86f83a7446c7e87ac4c47ec56/clpy/backend/memory.pyx#L295)/[writing](https://github.com/fixstars/clpy/blob/1542f0b9f4d686e86f83a7446c7e87ac4c47ec56/clpy/backend/memory.pyx#L304) memory, so `cl_event` parameters are not used usually.
- Batched sgemm/dgemm are made wait-free

2019-04-05 11:25 UTC, vorj commented
@LWisteria please review this PR.

2019-04-08 07:48 UTC, LWisteria requested changes
@vorj Diff looks good.

However, What does the PR title mean? It does't look "Refactoring" because the features of *Batched are changed (sync -> async).
Do you mean "removing waiting from *Batched"? The default params can be a minor edits for this PR.

2019-04-08 10:09 UTC, vorj commented
@LWisteria Ah, well, OK, so I'll change this PR's title, then the refactoring (I had thought that this one is the main of this PR... of course, as it is so, the second change exceeds _refactoring_ ) will be treated as minor edit in this PR.

2019-04-08 10:13 UTC, vorj commented
@LWisteria I did it. Please review it.

2019-04-09 01:55 UTC, LWisteria approved these changes
LGTM

2019-04-09 01:55 UTC, merged