Check cl_khr_fp16 support
fixstars/clpy pull request #225
Opened 2019-04-16 07:02 UTC by vorj

This PR is WIP now.

Task of #224 .
ClPy in this PR checks that the device supports `#pragma OPENCL EXTENSION cl_khr_fp16: enable` or not before first running kernel, and enable or disable `cl_khr_fp16` adequately.

Remaining tasks:
    - [ ] skip tests which have `half` output

2019-04-16 07:04 UTC, vorj commented
@nsakabe-fixstars Please check this branch. Does ClPy of this branch work on your environment?

2019-04-16 08:49 UTC, nsakabe-fixstars commented
@vorj I confirmed it working on NVIDIA GPU w/o fp16 feature. Thank you.

2019-04-19 16:42 UTC, vorj commented
@nsakabe-fixstars It's time to pass the baton. This PR has remaining tasks, so please push this forward. _You have!_

2019-05-23 06:44 UTC, nsakabe-fixstars commented
> skip tests which have half output

I ran the tests with 1080Ti(w/o fp16). Needed to skip:
```
test_fusion.py::TestFusionTrigonometric::test_arctan FAILED              [ 15%]
test_fusion.py::TestFusionTrigonometric::test_arctan2 FAILED             [ 16%]
test_fusion.py::TestFusionTrigonometric::test_cos FAILED                 [ 16%]
test_fusion.py::TestFusionTrigonometric::test_deg2rad FAILED             [ 16%]
test_fusion.py::TestFusionTrigonometric::test_hypot FAILED               [ 16%]
test_fusion.py::TestFusionTrigonometric::test_rad2deg FAILED             [ 16%]
test_fusion.py::TestFusionTrigonometric::test_sin FAILED                 [ 16%]
test_fusion.py::TestFusionTrigonometric::test_tan FAILED                 [ 16%]
test_fusion.py::TestFusionHyperbolic::test_arcsinh FAILED                [ 16%]
test_fusion.py::TestFusionHyperbolic::test_cosh FAILED                   [ 17%]
test_fusion.py::TestFusionHyperbolic::test_sinh FAILED                   [ 17%]
test_fusion.py::TestFusionHyperbolic::test_tanh FAILED                   [ 17%]
test_fusion.py::TestFusionRounding::test_ceil FAILED                     [ 17%]
test_fusion.py::TestFusionRounding::test_fix FAILED                      [ 17%]
test_fusion.py::TestFusionRounding::test_floor FAILED                    [ 17%]
test_fusion.py::TestFusionRounding::test_rint FAILED                     [ 17%]
test_fusion.py::TestFusionRounding::test_rint_negative FAILED            [ 17%]
test_fusion.py::TestFusionRounding::test_trunc FAILED                    [ 17%]
test_fusion.py::TestFusionExplog::test_exp FAILED                        [ 17%]
test_fusion.py::TestFusionExplog::test_exp2 FAILED                       [ 18%]
test_fusion.py::TestFusionExplog::test_expm1 FAILED                      [ 18%]
test_fusion.py::TestFusionExplog::test_log FAILED                        [ 18%]
test_fusion.py::TestFusionExplog::test_log10 FAILED                      [ 18%]
test_fusion.py::TestFusionExplog::test_log1p FAILED                      [ 18%]
test_fusion.py::TestFusionExplog::test_log2 FAILED                       [ 18%]
test_fusion.py::TestFusionExplog::test_logaddexp FAILED                  [ 18%]
test_fusion.py::TestFusionExplog::test_logaddexp2 FAILED                 [ 18%]
test_fusion.py::TestFusionFloating::test_copysign FAILED                 [ 18%]
test_fusion.py::TestFusionFloating::test_nextafter FAILED                [ 19%]
test_fusion.py::TestFusionMisc::test_sqrt FAILED                         [ 23%]
test_ndarray_complex_ops.py::TestAngle::test_angle FAILED                [ 64%]
test_arithmetic.py::TestArithmetic::test_angle FAILED                    [  1%]
test_explog.py::TestExplog::test_exp FAILED                              [ 12%]
test_explog.py::TestExplog::test_exp2 FAILED                             [ 12%]
test_explog.py::TestExplog::test_expm1 FAILED                            [ 13%]
test_explog.py::TestExplog::test_log FAILED                              [ 13%]
test_explog.py::TestExplog::test_log10 FAILED                            [ 14%]
test_explog.py::TestExplog::test_log1p FAILED                            [ 14%]
test_explog.py::TestExplog::test_log2 FAILED                             [ 15%]
test_explog.py::TestExplog::test_logaddexp FAILED                        [ 15%]
test_explog.py::TestExplog::test_logaddexp2 FAILED                       [ 16%]
test_floating.py::TestFloating::test_copysign FAILED                     [ 16%]
test_floating.py::TestFloating::test_nextafter FAILED                    [ 18%]
test_hyperbolic.py::TestHyperbolic::test_arcsinh FAILED                  [ 20%]
test_hyperbolic.py::TestHyperbolic::test_cosh FAILED                     [ 21%]
test_hyperbolic.py::TestHyperbolic::test_sinh FAILED                     [ 21%]
test_hyperbolic.py::TestHyperbolic::test_tanh FAILED                     [ 22%]
test_misc.py::TestMisc::test_sqrt FAILED                                 [ 56%]
test_rounding.py::TestRounding::test_ceil FAILED                         [ 57%]
test_rounding.py::TestRounding::test_fix FAILED                          [ 57%]
test_rounding.py::TestRounding::test_floor FAILED                        [ 58%]
test_rounding.py::TestRounding::test_rint FAILED                         [ 59%]
test_rounding.py::TestRounding::test_rint_negative FAILED                [ 59%]
test_rounding.py::TestRounding::test_trunc FAILED                        [ 60%]
test_trigonometric.py::TestTrigonometric::test_arctan FAILED             [ 89%]
test_trigonometric.py::TestTrigonometric::test_arctan2 FAILED            [ 90%]
test_trigonometric.py::TestTrigonometric::test_cos FAILED                [ 90%]
test_trigonometric.py::TestTrigonometric::test_deg2rad FAILED            [ 91%]
test_trigonometric.py::TestTrigonometric::test_hypot FAILED              [ 91%]
test_trigonometric.py::TestTrigonometric::test_rad2deg FAILED            [ 92%]
test_trigonometric.py::TestTrigonometric::test_sin FAILED                [ 92%]
test_trigonometric.py::TestTrigonometric::test_tan FAILED                [ 93%]
```

2020-02-04 06:03 UTC, vorj commented
@LWisteria The CI has passed. Please review this PR.

2020-02-04 06:07 UTC, vorj commented
Of course this PR is too ad-hoc, so we should use this as temporary solution and will revert this in the future if this PR will be merged.

2020-02-04 06:07 UTC, LWisteria requested changes
Skipping CI if no fp16 support is a bad idea. I won't approve of this PR.

2020-02-04 06:12 UTC, LWisteria commented
@vorj Removing CI tests needing fp16 support looks better for me.

2020-02-04 06:16 UTC, vorj commented
@LWisteria You mean that we should remove all of codes related to `half` (temporarily), right?

2020-02-04 07:15 UTC, LWisteria commented
@vorj Actually, you don't need to do that. It's just ideally better than this PR, that's why I won't approve.

2020-02-04 07:37 UTC, vorj commented
@LWisteria I didn't talk about my task, I just want to know what you told more correctly.

BTW, for my information, I want to know that the usecase of skipping test, because it seems that my opinion about that is wrong.
Do you know the location for some good description about that?

2020-02-04 10:37 UTC, LWisteria commented
@vorj As you know, the primary reason for the problem is ClPy's insufficiency of fp16 support.
Therefore, skipping some tests and/or disabling cl_khr_fp16 if the device doesn't support it will solve nothing, but just only pass CI.

Only passing CI must not be your goal.

2020-02-04 10:59 UTC, vorj commented
@LWisteria 

> Therefore, skipping some tests and/or disabling cl_khr_fp16 if the device doesn't support it will solve nothing, but just only pass CI.

This sentence is true, then what the difference between **removing** the test cases and **skipping** them? IMHO, removing tests will solve nothing as well as this PR.

> Only passing CI must not be your goal.

I haven't said that, I told that we should revert this in the future if we will merge this PR. I have never thought that this PR solves the core issue, but I think that broken CI should be fixed in short order.
As you said at #261 , the CI issue is caused by the environment broken of our secondary machine, but it means that users who install CUDA 10.2 can't use ClPy at thier own environment for now. I think that this should be fixed.

2020-02-04 11:17 UTC, LWisteria commented
> the difference between removing the test cases and skipping them

I meant that removing the test **from CI**, not from unit-tests itself, which guarantees functionalities of current and/or future ClPy.
Modifying the tests means that we decided to change our goal, to be compatible with CuPy as much as possible.

We don't have enough discussions to do that. And I won't agree with it now.

> I think that this should be fixed.

I agree. However, we must not treat symptoms, remove the bottom causes.

We don't have to hurry so much. Now you waste your costs for the symptomatic treatment.

2020-02-04 11:34 UTC, vorj commented
@LWisteria 

> I meant that removing the test from CI, not from unit-tests itself, which guarantees functionalities of current and/or future ClPy.
> Modifying the tests means that we decided to change our goal, to be compatible with CuPy as much as possible.

Ah, OK, I understand. Thank you for your explanation.
BTW, I think that it's painful task that removing the test cases from CI, because we need to list so many valid test cases like `test_fusion.py::TestFusionFloating::test_signbit` , and so on.
(Of course, I don't think that we should push forward this PR just because the task will be painful.)

> We don't have to hurry so much.

Hmm, well, any user doesn't make the ticket like #239 recently, so I kind of agree.

2020-02-04 11:37 UTC, vorj commented
> Now you waste your costs for the symptomatic treatment.

No, I **had wasted** (it's just joke).

2020-02-22 00:33 UTC, LWisteria commented
After #269, this PR is obsolete. I'm closing but not deleting this branch for the further development.

2020-02-22 00:33 UTC, closed without merging