SGEMM benchmark
fixstars/clpy pull request #250
Opened 2019-09-26 08:13 UTC by shusukeueda

#216 の続きで SGEMM/cp.dot のベンチマークの部分を実装しました。
とりあえず必要なところしか実装していないので追加するべきところなどあると思います。
コメントお願いいたします。

2019-09-26 08:14 UTC, shusukeueda commented
Flake のチェック落ちたので、修正します

2019-09-26 08:25 UTC, shusukeueda commented
@LWisteria レビューお願いいたします。

2019-09-27 01:29 UTC, shusukeueda commented
@LWisteria 一部修正したので、お手数ですが改めてレビューお願いいたします。

2019-09-27 01:39 UTC, LWisteria requested changes
@shusukeueda レビューしました

2019-09-27 01:39 UTC, LWisteria commented on clpy/backend/opencl/api.pyx
> +cpdef size_t eventRecord() except *:
このような（OpenCL API直でない）ヘルパー関数は、apiではなくutilityに置いてあるのでそちらへ移動してもらえますか？

2019-09-27 01:39 UTC, LWisteria commented on clpy/backend/opencl/api.pyx
> +import clpy.backend.opencl.env
envがapiをimportしているので循環参照になってしまう気がするんですが、大丈夫でしょうか・・・

2019-09-27 01:39 UTC, LWisteria commented on clpy/backend/stream.py
> +        # raise NotImplementedError("clpy does not supoort this")
この辺り残す意味はまったくないので、コメントアウトではなく消してもらえますか

2019-09-27 01:39 UTC, LWisteria commented on clpy/backend/stream.py
>          # runtime.eventRecord(self.ptr, stream.ptr)
こことかも消してください

2019-09-27 02:39 UTC, shusukeueda commented on clpy/backend/stream.py
> +        # raise NotImplementedError("clpy does not supoort this")
`clpy does not...` などは消します。
CuPy 由来の引数やエラー処理など (`block`、`disable_timing` など) はどうするべきでしょうか？
(CUDA のイベントと違うものなので消すか、あるいは似たような機能を実装するまでコメントアウトで残しておくべきですか)

2019-09-27 02:40 UTC, LWisteria commented on clpy/backend/stream.py
> +        # raise NotImplementedError("clpy does not supoort this")
CuPy由来のもので、実装できそうなものがあれば、TODOにしておいてください。
明らかにCUDA以外（つまりOpenCLでは）役に立たないものであれば消して良いと思います。

2019-09-27 03:09 UTC, shusukeueda commented on clpy/backend/opencl/api.pyx
> +cpdef size_t eventRecord() except *:
`eventRecord`、`eventSynchronize` を `utility` に移動しました。

2019-09-27 03:11 UTC, shusukeueda commented on clpy/backend/opencl/api.pyx
> +import clpy.backend.opencl.env
`eventRecord`、`eventSynchronize` を `utility` に移動したので解消されました。

2019-09-27 03:13 UTC, shusukeueda commented on clpy/backend/stream.py
> +        # raise NotImplementedError("clpy does not supoort this")
フラグ、ストリームの引数は TODO で残しておきました。

2019-09-27 03:14 UTC, shusukeueda commented on clpy/backend/stream.py
>          # runtime.eventRecord(self.ptr, stream.ptr)
`runtime` を呼んでいた部分のコメントを削除しました。

2019-09-27 03:17 UTC, shusukeueda commented
@yoshifuji レビューいただいた部分を修正しました。確認お願いいたします。

2019-09-27 03:28 UTC, LWisteria approved these changes
LGTM

2019-09-27 03:29 UTC, merged