Support calling clpy.random.rand() without any argument
fixstars/clpy pull request #255
Opened 2019-10-10 12:08 UTC by vorj

According to #169, current `clpy.random.rand()` can call only with one or more argument(s) at first.
(After `rand()` was called with argument, we can call it with no argument.)

This PR fixes #169 (above problem).

2019-10-10 12:42 UTC, vorj commented
@LWisteria please review this.

2019-11-07 06:18 UTC, LWisteria requested changes
Please add or enable the tests passed by this PR.

2019-11-07 06:19 UTC, LWisteria commented
@vorj I forgot the mention.

2019-11-20 06:44 UTC, LWisteria commented
This PR was replaced with #259. Closed with unmerged.

2019-11-20 06:44 UTC, closed without merging