implement clpy.backend.ultima.exec_ultima()
fixstars/clpy pull request #256
Opened 2019-10-10 14:26 UTC by vorj

Close #254.

- implemented `clpy.backend.ultima.exec_ultima()`
- replaced the code in `clpy/core/carray.pxi` and `tests/clpy_tests/opencl_tests/ultima_tests/utility.py::exec_ultima()` to new `exec_ultima()`

2019-10-11 07:41 UTC, vorj commented
@LWisteria please review this.

2019-11-07 06:09 UTC, LWisteria requested changes
LGTM

2019-11-07 06:10 UTC, LWisteria commented
@vorj I couldn't your review request because I'm not assigned this PR. Please don't forget to do it.

2019-11-07 06:11 UTC, LWisteria approved these changes

2019-11-07 06:15 UTC, LWisteria commented
Although travis-ci doesn't respond, I confirmed that [the test is passed](https://travis-ci.org/fixstars/clpy/builds/596142215). I'm merging with admin privilege.

2019-11-07 06:16 UTC, merged

2019-11-07 08:01 UTC, vorj commented
@LWisteria Oops, sorry. I've forgotten it...