Refactor _launch function
fixstars/clpy pull request #287
Opened 2020-04-22 06:34 UTC by y1r

2020-04-22 06:53 UTC, y1r commented
I'll check the test.

2020-04-22 08:09 UTC, LWisteria requested changes

2020-04-22 08:09 UTC, LWisteria commented on clpy/backend/function.pyx
> +                         core.ndarray a, int arg_number):
You need `except`.

2020-04-22 08:09 UTC, LWisteria commented on clpy/backend/function.pyx
> +            raise ValueError("Stride of dim {0} = {1}, but item size is {2}"
Is it possible to add tests for this exception?

2020-04-22 08:47 UTC, y1r commented on clpy/backend/function.pyx
> +                         core.ndarray a, int arg_number):
Fixed.

2020-06-05 04:49 UTC, ghost requested changes
数箇所、修正お願いします。

2020-06-05 04:49 UTC, nsakabe-fixstars commented on clpy/backend/function.pyx
> +cdef int _launch_imm(clpy.backend.opencl.types.cl_kernel kernel,
`immediate` は省略するほど長くないので `_launch_immediate` でお願いします

関数内の変数名の方はスコープが短めなので、（修正しなくても）どちらでもよいです

2020-06-05 04:49 UTC, nsakabe-fixstars commented on clpy/backend/function.pyx
> +    cdef _CIndexer indexer  # to keep lifetime until SetKernelArg
スコープがネストされなくなったのでこのコメントは不要でしょうか。

2020-06-05 04:49 UTC, nsakabe-fixstars commented on clpy/backend/function.pyx
> +    cdef _CArray arrayInfo  # to keep lifetime until SetKernelArg
_CIndexer の方と同様に、見通しが良くなったのでこのコメントは不要に思います。

2020-07-10 09:58 UTC, ghost approved these changes
LGTM

2020-07-10 09:59 UTC, merged

2020-07-11 05:42 UTC, y1r commented
Thanks!